// **************************
// -- DO NOT EDIT THIS FILE --
// --------------------------
// This file is automatically 
// generated by a custom webpack
// plugin, and handles all 
// template dependencies for you.
// Any changes you make to this 
// file will be overwritten the
// next time that you build.
// --------------------------
// **************************

module.exports = {
  image: require('../image/middleware.js')
};